"""依赖锁定测试。

不锁版本已经害过真实用户（GitHub Issue #3：装到新版 FastAPI 直接报错），
项目最近几个提交也都在擦 Jinja2 + Python 3.14 的屁股。
"""

import os
import re

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# 这个不锁死是有意的：YouTube 变得快，钉住版本等于几个月后音乐失效。
# Dockerfile 里另有 `pip install -U yt-dlp`，CI 每周重建带上最新版。
UNPINNED_ON_PURPOSE = {"yt-dlp"}


def _read(name):
    with open(os.path.join(_ROOT, name), encoding="utf-8") as f:
        return f.read()


def _requirements(name):
    """返回 [(包名, 是否钉了 ==)]。"""
    out = []
    for line in _read(name).splitlines():
        line = line.split("#")[0].strip()
        if not line or line.startswith("-"):
            continue
        m = re.match(r"^([A-Za-z0-9_.\-]+)", line)
        if m:
            out.append((m.group(1).lower(), "==" in line))
    return out


def test_直接依赖除白名单外都钉死了():
    loose = [n for n, pinned in _requirements("requirements.in")
             if not pinned and n not in UNPINNED_ON_PURPOSE]
    assert not loose, f"这些依赖没钉版本：{loose}"


def test_ytdlp_至少有下限():
    """不钉死，但也不能完全裸着 —— 得防住装到已知失效的老版本。"""
    line = next(l for l in _read("requirements.in").splitlines()
                if l.strip().startswith("yt-dlp"))
    assert ">=" in line


def test_锁文件包含传递依赖():
    """锁文件应当比直接依赖多得多，否则说明不是 pip-compile 生成的。"""
    direct = len(_requirements("requirements.in"))
    locked = len(_requirements("requirements.txt"))
    assert locked > direct * 2, f"锁文件只有 {locked} 项，直接依赖有 {direct} 项"


def test_锁文件是生成物():
    assert "autogenerated by pip-compile" in _read("requirements.txt")
    assert "autogenerated by pip-compile" in _read("requirements-dev.txt")


def test_锁文件与镜像用同一个_python_版本生成():
    """用 3.14 生成的锁装到 3.12 的镜像里可能缺包 —— 两边必须一致。"""
    header = _read("requirements.txt")
    m = re.search(r"pip-compile with Python (\d+\.\d+)", header)
    assert m, "锁文件头部没有 Python 版本信息"
    lock_py = m.group(1)

    dockerfile = _read("Dockerfile")
    d = re.search(r"FROM python:(\d+\.\d+)", dockerfile)
    assert d, "Dockerfile 没有钉住 Python 次版本"
    assert lock_py == d.group(1), (
        f"锁文件用 Python {lock_py} 生成，但镜像是 {d.group(1)}")

    ci = _read(os.path.join(".github", "workflows", "test.yml"))
    c = re.search(r"python-version: '(\d+\.\d+)'", ci)
    assert c and c.group(1) == lock_py, "CI 的 Python 版本和锁文件对不上"


def test_python_基础镜像钉了次版本():
    """python:3-slim 会跟着上游滚，Jinja2 那几次事故就是这么来的。"""
    m = re.search(r"^FROM python:(\S+)", _read("Dockerfile"), re.M)
    assert m and re.match(r"^\d+\.\d+", m.group(1)), \
        f"基础镜像 {m.group(1) if m else '?'} 没钉次版本"


def test_模板缓存没有被禁用():
    """禁用缓存是 Jinja2 + Python 3.14 的历史 workaround，上游已修。

    重新禁用会让每个请求都重新编译模板（实测 4.6ms vs 1.4 微秒）。
    """
    web_main = _read(os.path.join("web", "main.py"))
    assert "templates.env.cache = None" not in web_main
